re-prife/back-end

src/main/java/kr/hs/mirim/family/controller/GroupController.java
src/main/java/kr/hs/mirim/family/dto/request/JoinGroupRequest.java
src/main/java/kr/hs/mirim/family/entity/group/repository/GroupRepository.java
src/main/java/kr/hs/mirim/family/service/GroupService.java

1. DTO 유효성 검사
2. 회원 존재 여부 확인
3. GroupInviteCode에 해당하는 그룹 존재 여부 확인
4. 회원에 Group 정보 업데이트

#23 그룹 가입 기능

---

src/main/java/kr/hs/mirim/family/controller/UserController.java
src/main/java/kr/hs/mirim/family/dto/request/CreateUserRequest.java
src/main/java/kr/hs/mirim/family/entity/user/User.java
src/main/java/kr/hs/mirim/family/service/UserService.java

1. signUp -> createUser 메서드명 변경
2. UserSignUpDto -> CreateUserRequest로 DTO명 변경
3. user entity 생성 시 builder 매개변수 순서 변경
4. user entity 생성 시 이미지 이름에 기본값을 설정하지 않고 생성할 때 ""값으로 저장
5. 닉네임 변수 관련 내용 추가
6. user entity에 nickname 컬럼 추가
7. Exception 처리 - HttpStatus 확인

#33 회원 생성 기능 관련 리펙토링 

---

build.gradle
src/main/java/kr/hs/mirim/family/config/QueryDslConfig.java
src/main/java/kr/hs/mirim/family/controller/GroupController.java
src/main/java/kr/hs/mirim/family/dto/response/UserListResponse.java
src/main/java/kr/hs/mirim/family/entity/group/repository/GroupRepository.java
src/main/java/kr/hs/mirim/family/entity/group/repository/GroupRepositoryExtension.java
src/main/java/kr/hs/mirim/family/entity/group/repository/GroupRepositoryImpl.java
src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepository.java
src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepositoryExtension.java
src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepositoryImpl.java
src/main/java/kr/hs/mirim/family/service/GroupService.java
src/main/java/kr/hs/mirim/family/service/UserService.java

- 해당 API를 요청한 사용자의 정보는 반환하지 않는다. 
- QueryDSL 세팅도 함께 했다.
1. 그룹 존재 여부 확인
2. 유저 존재 여부 확인
3. API를 요청한 사용자의 정보를 제외한 그룹에 속한 유저의 정보 반환
```json
[
{
"userId": 2,
"userName": "min j",
"userNickname": "kiki",
"userImageName": ""
},
{
"userId": 3,
"userName": "min j",
"userNickname": "kiki",
"userImageName": ""
}
]
```

#24 그룹에 속한 유저 목록 반환 기능

---

src/main/java/kr/hs/mirim/family/controller/ChoreController.java
src/main/java/kr/hs/mirim/family/dto/request/CreateChoreRequest.java
src/main/java/kr/hs/mirim/family/entity/chore/Chore.java
src/main/java/kr/hs/mirim/family/entity/chore/ChoreCategory.java
src/main/java/kr/hs/mirim/family/entity/chore/ChoreCheck.java
src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepository.java
src/main/java/kr/hs/mirim/family/entity/group/repository/GroupRepository.java
src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepository.java
src/main/java/kr/hs/mirim/family/service/ChoreService.java

* groupId 혹은 담당자 Id가 존재하지 않는 경우 404 에러 처리
* enum에 존재하지 않는 value에 대하여 404에러 처리
* 값의 형식이 맞지 않는 경우 409에러 처리
* ChoreDate type : Date -> LocalDate로 변경

#6 집안일 당번을 직접 추가하는 기능 구현 

---

src/main/java/kr/hs/mirim/family/controller/UserController.java
src/main/java/kr/hs/mirim/family/dto/request/CheckUserPasswordRequest.java
src/main/java/kr/hs/mirim/family/service/UserService.java

* 회원 정보를 수정하기 전, 회원 인증을 위한 비밀번호를 확인하는 기능입니다.
* `passwordCheck`메서드를 이용하여 해당 회원의 비밀번호가 맞는지 확인하였습니다.
* `userId`를 통해 해당 회원이 존재하는지 확인하였습니다.
* 회원 탈퇴 시 사용하는 비밀번호 확인 또한 `passwordCheck`메서드를 이용하였습니다.

#60 회원 정보 수정을 위한 비밀번호를 인증하는 기능

---

src/main/java/kr/hs/mirim/family/controller/UserController.java
src/main/java/kr/hs/mirim/family/dto/request/UpdateUserRequest.java
src/main/java/kr/hs/mirim/family/entity/user/User.java
src/main/java/kr/hs/mirim/family/service/UserService.java

* 회원이 자신의 정보를 수정하는 기능입니다.
* 해당 기능을 실행하기에 앞서, 회원 인증을 위한 비밀번호 확인을 진행해야합니다.
* 수정하고자 하는 비밀번호를 받아, 암호화하여 DB에 저장하였습니다.
* 개별 수정이 아닌, 전체 수정으로 만약 일부만 수정하고자 한다면 전체에서 수정할 사항만 변경된 상태로 값을 받습니다.

#19 회원이 자신의 정보를 수정하는 기능

---

src/main/java/kr/hs/mirim/family/controller/IngredientController.java
src/main/java/kr/hs/mirim/family/dto/request/IngredientRequest.java
src/main/java/kr/hs/mirim/family/entity/ingredient/Ingredient.java
src/main/java/kr/hs/mirim/family/service/IngredientService.java

식재료의 수가 0개 또는 0g 등 0일 경우 식재료 삭제
식재료 추가할 때 0개로 들어오면 에러 처리
ingredient service를 선언할 때 service -> ingredeintService로 변경

#5 식재료 세부 사항 수정 기능 구현

---

src/main/java/kr/hs/mirim/family/controller/QuestController.java
src/main/java/kr/hs/mirim/family/dto/request/QuestRequest.java
src/main/java/kr/hs/mirim/family/dto/response/QuestResponse.java
src/main/java/kr/hs/mirim/family/entity/quest/Quest.java
src/main/java/kr/hs/mirim/family/service/QuestService.java

404 - Not Found
- groupId가 존재하지 않을 경우
- quest가 group에 속해있지 않을 경우
- user가 group에 속해있지 않을 경우
409 - Conflict
- quest를 생성한 user가 아닌 경우
405 methodNotAllowed
- 수락자가 있는 심부름을 수정하려는 경우

#10 심부름 수정 기능 구현

---

src/main/java/kr/hs/mirim/family/controller/ChoreController.java
src/main/java/kr/hs/mirim/family/service/ChoreService.java

204 - No Coment
- 당번이 제대로 삭제된 경우
404 - not found
- group Id가 존재하지 않을 경우
- chore id가 존재하지 않을 경우
409 - conflict
- 집안일이 그룹에 속하지 않은 경우
405 - method not allowed
- 완료된 집안일을 삭제하려는 경우

#14 집안일 삭제 기능

---

src/main/java/kr/hs/mirim/family/controller/IngredientController.java
src/main/java/kr/hs/mirim/family/dto/request/DeleteIngredientDataRequest.java
src/main/java/kr/hs/mirim/family/dto/request/DeleteIngredientRequest.java
src/main/java/kr/hs/mirim/family/service/IngredientService.java

반복문을 통해 들어온 모든 식재료 삭제
식재료가 하나도 없을 경우 400 에러 발생
식재료가 여러 개면 모두 삭제

#73 식재료 일괄 삭제 기능 구현

---

src/main/java/kr/hs/mirim/family/controller/GroupController.java
src/main/java/kr/hs/mirim/family/dto/request/ReportRequest.java
src/main/java/kr/hs/mirim/family/entity/group/Group.java
src/main/java/kr/hs/mirim/family/service/GroupService.java

204 - No content
- 그룹의 공지사항이 업데이트 될 경우
400 - Bad request
- request dto의 형식이 유효하지 않을 경우
404 - Not found
- group이 존재하지 않을 경우

#70 그룹의 공지사항 추가 기능 구현 

---

src/main/java/kr/hs/mirim/family/entity/ingredient/repository/IngredientRepositoryImpl.java
src/main/java/kr/hs/mirim/family/service/IngredientService.java

#76 식재료 관련 수정

---

src/main/java/kr/hs/mirim/family/controller/UserController.java
src/main/java/kr/hs/mirim/family/dto/response/UserFindKingResponse.java
src/main/java/kr/hs/mirim/family/dto/response/UserFindResponse.java
src/main/java/kr/hs/mirim/family/service/UserService.java

* 회원의 상세 정보를 조회하는 기능입니다.
* 회원의 이름, 별명, 이메일, 이미지명, 저번달 왕을 반환합니다.
* 왕을 계산할때, King에서 사용한 메서드를 함께 사용하였습니다.
* 만약, 왕이 아니였다면 null값 혹은 빈배열[]을 반환합니다.

#21 회원의 상세 정보를 조회하는 기능

---

src/main/java/kr/hs/mirim/family/service/GroupService.java
src/main/java/kr/hs/mirim/family/service/IngredientService.java

409 conflict
- 유통 기한이 구매 날짜보다 앞선 경우 에러

#94 식재료 에러 처리 추가

---

.github/workflows/gradle.yml
README.md
build.gradle
src/main/java/kr/hs/mirim/family/controller/QuestController.java
src/main/java/kr/hs/mirim/family/dto/request/CreateUserRequest.java
src/main/java/kr/hs/mirim/family/dto/response/QuestFindOneResponse.java
src/main/java/kr/hs/mirim/family/service/QuestService.java
src/test/resources/application.yml
src/test/resources/data.sql

release 1.0 -> main

---

src/main/java/kr/hs/mirim/family/dto/request/LoginUserRequest.java
src/main/java/kr/hs/mirim/family/dto/response/LoginUserResponse.java

* 배포 중 발생한 bug(에러)를 처리하였습니다.
* 기본생성자가 없는 request/response DTO에 기본생성자 어노테이션(`@NoArgsConstructor`)을 추가하였습니다.

#106 DTO 기본 생성자 추가 

---

src/main/java/kr/hs/mirim/family/dto/request/CreateUserRequest.java
src/main/java/kr/hs/mirim/family/dto/request/UpdateUserPasswordRequest.java

* 배포 중 발생한 bug(에러)를 처리하였습니다.
* 비밀번호의 최소길이가 8자리인지 확인하는 코드입니다.
* 비밀번호의 최소길이가 8자리 이하인 경우 BindingResult에서 형식이 옳지 않다는 예외를 반환합니다.

#112 비밀번호의 최소길이 확인

---

src/main/java/kr/hs/mirim/family/controller/UserController.java
src/main/java/kr/hs/mirim/family/dto/response/CreateUserResponse.java
src/main/java/kr/hs/mirim/family/service/UserService.java

#118 회원가입 후, 회원 정보 객체 반환

---

src/main/java/kr/hs/mirim/family/controller/GroupController.java
src/main/java/kr/hs/mirim/family/dto/response/GroupResponse.java
src/main/java/kr/hs/mirim/family/service/GroupService.java

```json
{
"groupId": 16,
"groupInviteCode": "LzfXVqC"
}
```

#122 그룹 가입 / 생성 시 그룹 초대 코드 반환하기

---

src/main/java/kr/hs/mirim/family/service/UserService.java

* 로그인 후 response로 `userImagePath`가 함께 반환됩니다.

#128 login시 이미지경로를 반환하는 기능

---

src/main/java/kr/hs/mirim/family/dto/response/IngredientListResponse.java
src/main/java/kr/hs/mirim/family/entity/ingredient/repository/IngredientRepositoryImpl.java
src/main/java/kr/hs/mirim/family/service/IngredientService.java

식재료 아이디, 구매날짜 추가
유통기한에 따른 색깔 추가(black, red, yellow, green)

#132 식재료 리스트 반환 컬럼 추가

---

src/main/java/kr/hs/mirim/family/service/UserService.java

* 회원 상세 조회시, 지난달 집안일과 심부름을 바탕으로 왕을 선정한 내용을 반환합니다.
* 받은 date의 한달 전 값을 바탕으로 왕을 계산하여 반환하였습니다.
* Warning 사항을 개선하였습니다.
* List에 사용할 객체 타입이 정해지지 않았다는 경고이므로, ArrayList 뒤에 해당 타입을 명시하고자 하였습니다
* 다만, `replaced with <>`라는 경고에 의해 중복된 코드를 삭제하고 <>만 작성하였습니다.

#139 회원 상세 조회 날짜 기능 수정

---

src/main/java/kr/hs/mirim/family/controller/GroupController.java
src/main/java/kr/hs/mirim/family/dto/response/GetGroupReportResponse.java
src/main/java/kr/hs/mirim/family/service/GroupService.java

- 공지사항이 등록되어있는 경우
```json
{
"groupReport": "안녕하세요"
}
```
- 공지사항이 없는 경우
```json
{
"groupReport": ""
}
```

#124 그룹의 공지사항을 조회하는 기능

---

src/main/java/kr/hs/mirim/family/config/MultipartConfig.java
src/main/java/kr/hs/mirim/family/dto/response/GroupResponse.java
src/main/java/kr/hs/mirim/family/dto/response/IngredientListResponse.java
src/main/java/kr/hs/mirim/family/service/ImageService.java
src/main/java/kr/hs/mirim/family/service/KingService.java
src/main/resources/application.yml

#152 이미지 관련 수정

---

src/main/java/kr/hs/mirim/family/controller/NotificationController.java
src/main/java/kr/hs/mirim/family/controller/QuestController.java
src/main/java/kr/hs/mirim/family/controller/UserController.java
src/main/java/kr/hs/mirim/family/dto/response/CreateUserResponse.java
src/main/java/kr/hs/mirim/family/dto/response/QuestNotificationResponse.java
src/main/java/kr/hs/mirim/family/service/NotificationService.java
src/main/java/kr/hs/mirim/family/service/QuestService.java
src/main/java/kr/hs/mirim/family/service/UserService.java

#120 심부름 생성 시 그룹원에게 알림을 보내는 기능

---

src/main/java/kr/hs/mirim/family/service/ImageService.java

확장자를 이미지 이름에서 가져와서 정했으나 확장자를 붙인 이름이 넘어오지 않아 변경

#163 이미지 확장자 고정 처리

---

src/main/java/kr/hs/mirim/family/dto/response/LoginUserResponse.java
src/main/java/kr/hs/mirim/family/service/UserService.java

* 회원 로그인시, 기존 반환값에 groupInviteCode를 함께 반환합니다.

#166 로그인시, 그룹 초대 코드를 반환하는 기능

---

src/test/java/kr/hs/mirim/family/controller/UserControllerTest.java

* 그룹없는 회원의 로그인 기능 수정으로 인해 발생하는 테스트코드의 예외를 다시 작성하였습니다.

#179 그룹없는 회원 로그인 기능 수정으로 인한 테스트 코드 변경

---

src/main/java/kr/hs/mirim/family/dto/response/QuestFindOneResponse.java
src/main/java/kr/hs/mirim/family/service/QuestService.java

```json
{
"requestUserId": 11,
"questTitle": "ahahahfnlkp",
"questContent": "제발",
"completeCheck": false,
"acceptUserId": 5,
"questCreatedDate": "2022-06-15"
}
```

#183 심부름 상세 조회 시 심부름의 내용도 함께 반환 

---

src/main/java/kr/hs/mirim/family/controller/NotificationController.java
src/main/java/kr/hs/mirim/family/controller/QuestController.java
src/main/java/kr/hs/mirim/family/dto/request/QuestRequest.java
src/main/java/kr/hs/mirim/family/dto/response/QuestNotificationResponse.java
src/main/java/kr/hs/mirim/family/entity/group/repository/GroupRepository.java
src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepository.java
src/main/java/kr/hs/mirim/family/service/NotificationService.java
src/main/java/kr/hs/mirim/family/service/QuestService.java
src/test/java/kr/hs/mirim/family/controller/QuestControllerTest.java

#178 요청된 심부름 수락 시 요청자에게 알림을 보내는 기능 구현

---

src/main/java/kr/hs/mirim/family/service/ImageService.java
src/main/java/kr/hs/mirim/family/service/IngredientService.java
src/test/java/kr/hs/mirim/family/controller/IngredientControllerTest.java

식재료 수정, 식재료 개수 일괄 수정, 식재료 일괄 삭제에서 사용함

#159 서버에 저장된 이미지 삭제 기능 구현

---

src/main/java/kr/hs/mirim/family/controller/ChoreController.java
src/main/java/kr/hs/mirim/family/dto/response/ChoreCertifyReactionResponse.java
src/main/java/kr/hs/mirim/family/service/ChoreService.java

* 클라이언트와의 web socket 연결시 해당 집안일 당번의 아이디가 필요하여 집안일 인증 요청 후 해당 집안일 당번 아이디를 반환하였습니다.

#196 집안일 응답시, 집안일 당번 아이디 반환하는 기능

---

src/main/java/kr/hs/mirim/family/entity/quest/repository/QuestRepositoryImpl.java

이달의 왕의 이름과 이미지 경로가 맞지 않았기 때문에 user_tb와 join 후 처리

#203 이달의 왕의 아이디와 이름이 맞지 않는 문제 수정
